/**
 * The reproduction seam.
 *
 * `packages/reproduce` is being built in parallel. This file is the LOCAL contract the UI
 * renders against, so the panel is finished and testable before that package lands: swap
 * `reproductionFor()` for a call into the package and delete the fixtures, and no component
 * changes.
 *
 * The four states are exhaustive and all four are first class. `refused` and
 * `not_configured` in particular are not error states and must never render as one:
 *
 *   succeeded           we remade the artifact, here is how long it took
 *   could_not_reproduce we tried and failed. That is a result about US, not about the work
 *   refused             we declined on purpose (an identifiable person, a licensed work,
 *                       no consent on file). Refusing is a feature; see
 *                       publicity-defamation-risk.md Tier 1 item 6
 *   not_configured      no reproduction pipeline is wired for this modality in this build
 *
 * The one rule the type cannot enforce and the component must: whenever `succeeded` puts
 * the original and the recreation in the same view, the disclaimer band ships inside the
 * same frame, at the same pixel height as the panel labels, with symmetric panels. That is
 * a legal requirement (equal prominence), not a styling preference.
 */

export interface Plate {
  readonly src: string;
  /** What is depicted. The recreation's alt is forced to open with the disclosure. */
  readonly describes: string;
  readonly width: number;
  readonly height: number;
  /** Rendered under the plate, in mono. "provided by you, 1024x640". */
  readonly meta: string;
}

export interface ReproductionSucceeded {
  readonly state: "succeeded";
  /** Measured, not estimated. The largest object on the receipt is this number. */
  readonly elapsedMs: number;
  readonly submitted: Plate;
  readonly recreation: Plate;
  /** The pipeline that produced the recreation, named so the run can be repeated. */
  readonly pipeline: string;
  /** Rule id whose evidence carries the prompt, so the claim is cited like any other. */
  readonly promptCitedBy?: string;
}

export interface ReproductionCouldNotReproduce {
  readonly state: "could_not_reproduce";
  readonly attemptedMs: number;
  readonly submitted?: Plate;
  /** What stopped us. Phrased as a fact about our pipeline. */
  readonly reason: string;
}

export interface ReproductionRefused {
  readonly state: "refused";
  readonly code: "identifiable_person" | "licensed_work" | "no_consent_on_file";
  readonly reason: string;
}

export interface ReproductionNotConfigured {
  readonly state: "not_configured";
  readonly modality: string;
  readonly reason: string;
}

export type Reproduction =
  | ReproductionSucceeded
  | ReproductionCouldNotReproduce
  | ReproductionRefused
  | ReproductionNotConfigured;

/**
 * Fixed copy. Not rewritten for tone, not shortened for layout, not moved out of the frame.
 * Rendered at 14px mono in --ink, byte-identical in size and colour to the panel labels.
 */
export const DISCLAIMER_HEADING = "READ THIS WITH THE IMAGES ABOVE";

export const DISCLAIMER_BODY =
  "The right-hand panel was generated by us, moments ago, from the prompt listed in the evidence below. It is not evidence about who made the left-hand panel, or how they made it. We make no claim that any person used a generative model. What is shown is one fact only: this artifact is cheap to reproduce.";

/** Prefix the recreation plate's alt text must open with, so images-off carries it too. */
export const RECREATION_ALT_PREFIX = "Recreation generated by Slop Scorer:";

export const recreationAlt = (describes: string): string =>
  `${RECREATION_ALT_PREFIX} ${describes}`;

/**
 * Fixtures, keyed by receipt id, standing in for `packages/reproduce`.
 *
 * Every artifact referenced here was made by us for this page. We do not put a recreation
 * of someone else's work in our own marketing surface, ever: that is a hard rule from the
 * legal memo and it applies to sample data exactly as much as to production output.
 */
const FIXTURES: Readonly<Record<string, Reproduction>> = {
  "4F2A-9C": {
    state: "succeeded",
    elapsedMs: 8400,
    pipeline: "layout transcription, then a single render pass. No model in the scoring path.",
    promptCitedBy: "css.violet-blue-gradient",
    submitted: {
      src: "/samples/4F2A-9C-submitted.svg",
      describes:
        "A marketing landing page: a violet-to-blue gradient band, one very large bold headline, and a row of three identical bordered cards.",
      width: 1024,
      height: 640,
      meta: "submitted for this sample by us, 1024x640",
    },
    recreation: {
      src: "/samples/4F2A-9C-recreation.svg",
      describes:
        "the same layout rebuilt from the measurements listed below: the same gradient band, headline block and three-card row.",
      width: 1024,
      height: 640,
      meta: "just now, 8.4 s, prompt in the evidence below",
    },
  },
  "8B10-2D": {
    state: "could_not_reproduce",
    attemptedMs: 21300,
    reason:
      "The upload is a re-encoded screenshot. Our pipeline could not recover the layout measurements it needs to rebuild the page, so it stopped instead of producing something that merely looks similar. A convincing recreation built from a guess would be the dishonest output here.",
  },
  "C7E3-51": {
    state: "refused",
    code: "identifiable_person",
    reason:
      "The artifact contains an identifiable face. We do not regenerate identifiable people, at any resolution, with or without a disclaimer. This is a standing refusal in the pipeline rather than a decision made per request.",
  },
  "A05E-13": {
    state: "not_configured",
    modality: "web page behind a login",
    reason:
      "The reproduction pipeline is not wired to authenticate, so nothing was attempted on this artifact. There is nothing to show, and an empty pair of panels here would imply we tried and failed, which is a different claim.",
  },
};

export function reproductionFor(receiptId: string): Reproduction {
  return (
    FIXTURES[receiptId] ?? {
      state: "not_configured",
      modality: "web page",
      reason:
        "No reproduction was requested for this receipt. The findings below stand on their own citations.",
    }
  );
}
