/**
 * The sample plates, as source text, so the export route never touches the filesystem.
 *
 * The receipt page serves these two files from `public/samples/`. The export route has to draw
 * the SAME artwork into its PNG, because an export that shows something other than the page it
 * came from is a different document wearing the page's receipt number.
 *
 * Reading them from `public/` at request time was the obvious approach and it is the wrong one:
 * the static directory is not part of a serverless function's traced input, so the route would
 * work locally and fail in production, on the one code path whose failure mode is legal rather
 * than cosmetic. So the markup lives here, in the bundle, and `apps/web/test/plate-svg.test.ts`
 * asserts each constant is byte-for-byte identical to the file the browser is served. Drift
 * between the two is a test failure rather than a discrepancy nobody notices.
 *
 * GENERATED FILE. To change a plate, edit the SVG in `apps/web/public/samples/` and re-run
 * `node scripts/sync-sample-plates.mjs` from the repository root.
 */

/** Byte for byte the contents of `public/samples/4F2A-9C-submitted.svg`. `apps/web/test/plate-svg.test.ts` proves it. */
export const SUBMITTED_PLATE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 640" width="1024" height="640" role="img" aria-label="A generated-looking marketing page: a violet to blue gradient band, one very large bold headline, and a row of three identical bordered cards.">
  <title>Fixture: a template-shaped marketing page, generated by us for this sample</title>
  <!--
    This file is a fixture WE MADE for the sample receipt. It is not a screenshot of anybody
    else's site. We never put a recreation of somebody else's work in our own marketing, and
    a sample receipt is marketing.

    It is drawn to carry, literally, the tells the sample receipt cites: the violet-to-blue
    gradient (css.violet-blue-gradient), the oversized heavy headline with crushed tracking
    (css.crushed-tracking), and three identical cards with a 16px radius and a two-layer
    shadow (dom.uniform-cards).
  -->
  <defs>
    <linearGradient id="s-hero" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#6366F1"/>
      <stop offset="100%" stop-color="#3B82F6"/>
    </linearGradient>
    <filter id="s-card" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="1" stdDeviation="1" flood-color="#000000" flood-opacity="0.05"/>
      <feDropShadow dx="0" dy="6" stdDeviation="8" flood-color="#000000" flood-opacity="0.08"/>
    </filter>
  </defs>

  <rect width="1024" height="640" fill="#FFFFFF"/>
  <rect width="1024" height="300" fill="url(#s-hero)"/>

  <rect x="64" y="36" width="96" height="12" rx="6" fill="#FFFFFF" fill-opacity="0.85"/>
  <rect x="784" y="34" width="52" height="16" rx="8" fill="#FFFFFF" fill-opacity="0.55"/>
  <rect x="852" y="34" width="52" height="16" rx="8" fill="#FFFFFF" fill-opacity="0.55"/>
  <rect x="920" y="30" width="40" height="24" rx="12" fill="#FFFFFF" fill-opacity="0.9"/>

  <rect x="452" y="96" width="120" height="24" rx="12" fill="#FFFFFF" fill-opacity="0.28"/>
  <rect x="152" y="144" width="720" height="40" rx="4" fill="#FFFFFF" fill-opacity="0.95"/>
  <rect x="232" y="196" width="560" height="40" rx="4" fill="#FFFFFF" fill-opacity="0.95"/>
  <rect x="332" y="256" width="360" height="14" rx="7" fill="#FFFFFF" fill-opacity="0.7"/>

  <g filter="url(#s-card)">
    <rect x="64" y="368" width="288" height="200" rx="16" fill="#FFFFFF" stroke="#E5E7EB"/>
    <rect x="368" y="368" width="288" height="200" rx="16" fill="#FFFFFF" stroke="#E5E7EB"/>
    <rect x="672" y="368" width="288" height="200" rx="16" fill="#FFFFFF" stroke="#E5E7EB"/>
  </g>

  <g fill="#E5E7EB">
    <rect x="96" y="400" width="32" height="32" rx="8"/>
    <rect x="400" y="400" width="32" height="32" rx="8"/>
    <rect x="704" y="400" width="32" height="32" rx="8"/>
  </g>
  <g fill="#111827" fill-opacity="0.85">
    <rect x="96" y="452" width="160" height="14" rx="4"/>
    <rect x="400" y="452" width="160" height="14" rx="4"/>
    <rect x="704" y="452" width="160" height="14" rx="4"/>
  </g>
  <g fill="#9CA3AF">
    <rect x="96" y="482" width="224" height="10" rx="5"/>
    <rect x="96" y="502" width="192" height="10" rx="5"/>
    <rect x="400" y="482" width="224" height="10" rx="5"/>
    <rect x="400" y="502" width="192" height="10" rx="5"/>
    <rect x="704" y="482" width="224" height="10" rx="5"/>
    <rect x="704" y="502" width="192" height="10" rx="5"/>
  </g>

  <rect x="64" y="600" width="896" height="1" fill="#E5E7EB"/>
</svg>
`;

/** Byte for byte the contents of `public/samples/4F2A-9C-recreation.svg`. `apps/web/test/plate-svg.test.ts` proves it. */
export const RECREATION_PLATE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 640" width="1024" height="640" role="img" aria-label="The same layout rebuilt from measurements: the same gradient band, the same headline block, and the same three-card row, with small differences in the copy blocks.">
  <title>Recreation generated by Slop Scorer from the measurements in the receipt</title>
  <!--
    The recreation. Built from the measured values the receipt cites, not by copying the file
    beside it: same gradient stops, same headline mass, same three-card row at the same radius
    and the same two-layer shadow.

    It is deliberately not pixel-identical. The line lengths in the card bodies differ, which
    is what a rebuild from measurements actually produces. A recreation that matched byte for
    byte would be a copy, and would be making a claim about the original we are not making.
  -->
  <defs>
    <linearGradient id="r-hero" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#6366F1"/>
      <stop offset="100%" stop-color="#3B82F6"/>
    </linearGradient>
    <filter id="r-card" x="-20%" y="-20%" width="140%" height="140%">
      <feDropShadow dx="0" dy="1" stdDeviation="1" flood-color="#000000" flood-opacity="0.05"/>
      <feDropShadow dx="0" dy="6" stdDeviation="8" flood-color="#000000" flood-opacity="0.08"/>
    </filter>
  </defs>

  <rect width="1024" height="640" fill="#FFFFFF"/>
  <rect width="1024" height="300" fill="url(#r-hero)"/>

  <rect x="64" y="36" width="88" height="12" rx="6" fill="#FFFFFF" fill-opacity="0.85"/>
  <rect x="788" y="34" width="48" height="16" rx="8" fill="#FFFFFF" fill-opacity="0.55"/>
  <rect x="852" y="34" width="56" height="16" rx="8" fill="#FFFFFF" fill-opacity="0.55"/>
  <rect x="924" y="30" width="36" height="24" rx="12" fill="#FFFFFF" fill-opacity="0.9"/>

  <rect x="456" y="96" width="112" height="24" rx="12" fill="#FFFFFF" fill-opacity="0.28"/>
  <rect x="152" y="144" width="720" height="40" rx="4" fill="#FFFFFF" fill-opacity="0.95"/>
  <rect x="248" y="196" width="528" height="40" rx="4" fill="#FFFFFF" fill-opacity="0.95"/>
  <rect x="344" y="256" width="336" height="14" rx="7" fill="#FFFFFF" fill-opacity="0.7"/>

  <g filter="url(#r-card)">
    <rect x="64" y="368" width="288" height="200" rx="16" fill="#FFFFFF" stroke="#E5E7EB"/>
    <rect x="368" y="368" width="288" height="200" rx="16" fill="#FFFFFF" stroke="#E5E7EB"/>
    <rect x="672" y="368" width="288" height="200" rx="16" fill="#FFFFFF" stroke="#E5E7EB"/>
  </g>

  <g fill="#E5E7EB">
    <rect x="96" y="400" width="32" height="32" rx="8"/>
    <rect x="400" y="400" width="32" height="32" rx="8"/>
    <rect x="704" y="400" width="32" height="32" rx="8"/>
  </g>
  <g fill="#111827" fill-opacity="0.85">
    <rect x="96" y="452" width="148" height="14" rx="4"/>
    <rect x="400" y="452" width="172" height="14" rx="4"/>
    <rect x="704" y="452" width="156" height="14" rx="4"/>
  </g>
  <g fill="#9CA3AF">
    <rect x="96" y="482" width="216" height="10" rx="5"/>
    <rect x="96" y="502" width="176" height="10" rx="5"/>
    <rect x="400" y="482" width="228" height="10" rx="5"/>
    <rect x="400" y="502" width="200" height="10" rx="5"/>
    <rect x="704" y="482" width="208" height="10" rx="5"/>
    <rect x="704" y="502" width="184" height="10" rx="5"/>
  </g>

  <rect x="64" y="600" width="896" height="1" fill="#E5E7EB"/>
</svg>
`;

/** The one place a plate URL becomes pixels. An unknown path is not guessed at. */
export const PLATE_SVG_BY_SRC: Readonly<Record<string, string>> = {
  "/samples/4F2A-9C-submitted.svg": SUBMITTED_PLATE_SVG,
  "/samples/4F2A-9C-recreation.svg": RECREATION_PLATE_SVG,
};
