/**
 * Assessment status, and the sentence we are allowed to print.
 *
 * Modelled on Stripe Radar's output contract, which is the only shipped, at-scale, legally
 * survivable version of "score a stranger's artifact and say something about it". Three of
 * its design decisions are copied here deliberately:
 *
 *  1. THE ABSTENTION STATES ARE ENUM VALUES IN THE API TYPE, not a UI garnish. Radar ships
 *     `not_assessed` ("your business has opted out") and `unknown` ("something went wrong")
 *     as first-class `outcome.type` values with their own documented reason strings. A
 *     consumer of this API therefore cannot accidentally read an abstention as a low score,
 *     because the score field is `null` and the status field says which kind of silence it
 *     is. `inconclusive` (we looked and cannot say) and `not_assessed` (we did not look) are
 *     different facts and are never collapsed.
 *  2. THE SCORE NEVER REACHES CERTAINTY. Radar's range is 0-99, not 0-100, so "100% AI" does
 *     not exist as a screenshot. `MAX_SCORE` is 99 here for the same reason, and it is
 *     enforced in the scoring path rather than in a formatter.
 *  3. THE VERDICT DESCRIBES WHAT WE DID, NEVER WHAT THE SUBJECT IS. Radar's seller-facing
 *     strings are "Stripe blocked this charge as too risky", not "this customer is a
 *     fraudster". Every sentence `verdictSentence` can emit has the same grammar: the
 *     subject is us, the object is the artifact, and the verb is an action we took. It
 *     cannot describe a person, because the inputs it is given never contain one.
 *
 * `publicity-defamation-risk.md` supplies the reason this is a type and not a style guide:
 * *In re Workado* makes an accuracy claim about an inference a substantiation-bearing
 * statement under FTC Act s5. A sentence that says what we measured is defensible by
 * showing the measurement. A sentence that says what someone did is defensible only by
 * proving what they did, which we cannot do.
 */

/** The three states a result can be in. Exhaustive, and `score` is null for two of them. */
export type AssessmentStatus =
  /** We examined the artifact and the engine produced a score. */
  | "assessed"
  /** We examined the artifact and will not report a score. See `AbstentionReason`. */
  | "inconclusive"
  /** We did not examine the artifact at all. Not a low score, not a clean bill. */
  | "not_assessed";

/**
 * Why a score was withheld. Codes, not prose, so an appeal, a dashboard filter and a
 * calibration run can all agree on what happened without parsing a sentence.
 */
export type AbstentionCode =
  // inconclusive: we looked, and the read is not good enough to publish a number
  | "coverage_below_floor"
  | "single_family_only"
  | "probe_failed"
  // not_assessed: we did not look
  | "no_detector_for_input"
  | "out_of_scope_modality"
  | "detector_unavailable"
  | "opted_out";

export interface AbstentionReason {
  readonly code: AbstentionCode;
  /** Plain language, shown to the user verbatim. Says what we did, never what they are. */
  readonly detail: string;
}

/** Which status a code belongs to. Keeps the two kinds of silence from being conflated. */
export const ABSTENTION_STATUS: Readonly<Record<AbstentionCode, "inconclusive" | "not_assessed">> = {
  coverage_below_floor: "inconclusive",
  single_family_only: "inconclusive",
  probe_failed: "inconclusive",
  no_detector_for_input: "not_assessed",
  out_of_scope_modality: "not_assessed",
  detector_unavailable: "not_assessed",
  opted_out: "not_assessed",
};

/**
 * The ceiling. 99, never 100.
 *
 * A bounded scale that cannot express certainty is a structural constraint on what the
 * product can be quoted as saying. There is no threshold, prior or weight combination that
 * produces "100".
 */
export const MAX_SCORE = 99 as const;
export const MIN_SCORE = 0 as const;

/**
 * The words this product does not put in a sentence about somebody else's work.
 *
 * Checked by a test against every string `verdictSentence` can emit. The list is short and
 * concrete on purpose: it is not a tone guide, it is the set of phrasings that turn a
 * measurement into an allegation about a person's conduct.
 */
export const FORBIDDEN_VERDICT_PHRASES: readonly string[] = [
  "you ",
  "your ",
  "the author",
  "the creator",
  "the designer",
  "the developer",
  "wrote this",
  "made by ai",
  "ai-generated",
  "ai generated",
  "generated by",
  "is fake",
  "is a fake",
  "plagiar",
  "cheat",
  "lied",
  "dishonest",
  "fraud",
];

export interface VerdictInput {
  readonly status: AssessmentStatus;
  readonly score: number | null;
  readonly bandLabel: string;
  readonly rulesFired: number;
  readonly rulesEvaluated: number;
  readonly corpusVersion: string;
  readonly coverageRatio: number;
  readonly reasons: readonly AbstentionReason[];
}

/**
 * The one sentence the product is allowed to lead with.
 *
 * Grammar is fixed: WE did SOMETHING to THIS ARTIFACT, and here is the count. No adjective
 * describes the artifact's origin and no clause has a person as its subject. The number of
 * rules that did NOT fire is always printed next to the number that did, because "7 signals"
 * and "7 of 61 signals" are different claims and only the second one is true.
 */
export function verdictSentence(v: VerdictInput): string {
  if (v.status === "not_assessed") {
    const why = v.reasons[0]?.detail ?? "no detector in this build accepts this kind of input.";
    return `We did not assess this artifact: ${why}`;
  }
  if (v.status === "inconclusive") {
    const why = v.reasons.map((r) => r.detail).join(" ");
    return (
      `We examined this artifact and are not reporting a score. ` +
      `We read ${Math.round(v.coverageRatio * 100)}% of what we planned to read. ${why}`
    );
  }
  return (
    `We checked this artifact against ${v.rulesEvaluated} deterministic rules from ${v.corpusVersion} ` +
    `and ${v.rulesFired} matched, on ${Math.round(v.coverageRatio * 100)}% coverage. ` +
    `That places it in the "${v.bandLabel}" band at ${v.score} of ${MAX_SCORE}. Every match below cites what we read and where.`
  );
}
