/**
 * The only sentences this package is allowed to emit.
 *
 * `@slop/core` has `FORBIDDEN_VERDICT_PHRASES` for the scoring path. This is its mirror for the
 * reproduction path, and the reproduction path needs a STRONGER rule, because its output is more
 * persuasive: `market-check-reproduction.md` (e) names inverse harassment as the single biggest
 * risk in the product, on the reasoning that a convincing side-by-side reads as a verdict in a way
 * a percentage never does, and travels further.
 *
 * Two rules, both enforced at construction time by `assertPermitted` and both mutation-tested:
 *
 *  1. A BANNED-PHRASE LIST, inherited wholesale from core and extended. Inheriting rather than
 *     re-typing is deliberate: a phrase added to core's list must not be sayable here either, and
 *     a copied list drifts.
 *
 *  2. AN ATTRIBUTION RULE, which is the one that actually does the work. Any sentence containing
 *     a generation verb must attribute that generation to US, or be a negation. This is the
 *     "state only what is verifiable about our own action" requirement from
 *     `publicity-defamation-risk.md` Tier 1 #2, expressed as something a machine can check.
 *     "We remade this in 8.4 seconds" passes. "This was generated by a model" does not, and no
 *     amount of hedging gets it through, because the subject is wrong rather than the confidence.
 *
 * The carve-out for `X by us` is narrow and named: the ONLY permitted completion of a generation
 * verb plus "by" is this product. `design/SURFACES.md` requires the right-hand panel be labelled
 * as ours in the figure itself, so the phrase has to be sayable, and it is safe precisely because
 * it names the actor.
 */

import { FORBIDDEN_VERDICT_PHRASES } from "@slop/core";

/** Verbs that assert something was brought into existence. */
const GENERATION_VERBS = [
  "generated",
  "produced",
  "created",
  "made",
  "remade",
  "reproduced",
  "recreated",
  "wrote",
  "written",
  "drew",
  "drawn",
  "rendered",
  "faked",
];

/**
 * The actor a generation verb is allowed to name.
 *
 * Word-bounded on purpose: a substring test here would read "focus" as "us" and quietly accept
 * an unattributed claim, which is the class of silent-pattern failure this repository's meta
 * suite exists to catch.
 */
const FIRST_PERSON = [/\bwe\b/, /\bwe'/, /\bour\b/, /\bus\b/, /slop scorer/];

/** Markers that make a sentence a denial rather than an assertion. */
const NEGATIONS = ["not ", "no ", "never", "cannot", "nothing", "without "];

/**
 * Phrases that are never emitted, whatever the surrounding grammar.
 *
 * Core's list plus the reproduction-specific ones. The additions fall into three groups:
 * claims that the original is machine-made, claims that the original is human-made (the inverse
 * accusation, and just as unsubstantiable), and the vocabulary of certainty that turns a
 * measurement into a finding.
 */
export const FORBIDDEN_CLAIM_PHRASES: readonly string[] = [
  ...FORBIDDEN_VERDICT_PHRASES,
  // ...it is machine-made
  "this is ai",
  "was faked",
  "is faked",
  "used ai",
  "used a model",
  "used a generator",
  "passed off",
  "undisclosed",
  // ...it is human-made. Never a clean bill of health, never a green check, never a human score.
  "is human",
  "was human",
  "human-made",
  "human made",
  "made by a human",
  "made by hand",
  "verified human",
  "human score",
  "genuine",
  "authentic",
  // ...the vocabulary of certainty
  "confidence",
  "probability",
  "likely ai",
  "detected",
  "caught",
  "proof that",
  "proves",
];

/**
 * Verbatim statutory quotations, stripped before matching.
 *
 * There is exactly one, and it is the TAKE IT DOWN Act's definition of consent. It contains the
 * word "fraud", which core's list bans and should ban: in a sentence of ours about somebody's
 * work it is an allegation. Here it is part of a quoted definition of what the SUBMITTER's own
 * authorization has to be, which is the opposite kind of statement.
 *
 * A test pins this list at length one. An allowlist that can grow quietly is a hole, and this one
 * is the only place in the package where the guard can be told to look away.
 */
export const PERMITTED_VERBATIM_QUOTATIONS: readonly string[] = [
  "affirmative, conscious, and voluntary authorization, free from force, fraud, duress, misrepresentation, or coercion",
];

export interface ClaimViolation {
  readonly sentence: string;
  readonly kind: "forbidden_phrase" | "unattributed_generation";
  readonly detail: string;
}

export class ForbiddenClaimError extends Error {
  constructor(readonly violations: readonly ClaimViolation[]) {
    super(
      `This package may only state what WE did. ${violations.length} violation(s):\n` +
        violations.map((v) => `  - [${v.kind}] ${v.detail}\n    in: ${v.sentence}`).join("\n"),
    );
    this.name = "ForbiddenClaimError";
  }
}

/** Split on sentence terminators AND newlines, so a label or a list item is checked too. */
export function sentencesOf(text: string): string[] {
  return text
    .split(/(?<=[.!?])\s+|\n+/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/**
 * Neutralise the one permitted attribution before phrase matching.
 *
 * Exported so the test can assert the carve-out is exactly this narrow and nothing wider.
 */
export function neutralizeSelfAttribution(sentence: string): string {
  return sentence.replace(
    new RegExp(`\\b(${GENERATION_VERBS.join("|")})\\s+by\\s+(us|slop scorer)\\b`, "gi"),
    "$1",
  );
}

export function findClaimViolations(text: string): ClaimViolation[] {
  const out: ClaimViolation[] = [];
  let scannable = text;
  for (const quotation of PERMITTED_VERBATIM_QUOTATIONS) scannable = scannable.split(quotation).join("");
  for (const sentence of sentencesOf(scannable)) {
    const lower = sentence.toLowerCase();
    const neutral = neutralizeSelfAttribution(lower);
    for (const phrase of FORBIDDEN_CLAIM_PHRASES) {
      if (neutral.includes(phrase)) {
        out.push({
          sentence,
          kind: "forbidden_phrase",
          detail: `contains the forbidden phrase ${JSON.stringify(phrase)}`,
        });
      }
    }
    const verb = GENERATION_VERBS.find((v) => new RegExp(`\\b${v}\\b`).test(lower));
    if (verb !== undefined) {
      const attributed = FIRST_PERSON.some((p) => p.test(lower));
      const negated = NEGATIONS.some((n) => lower.includes(n));
      if (!attributed && !negated) {
        out.push({
          sentence,
          kind: "unattributed_generation",
          detail: `uses the generation verb ${JSON.stringify(verb)} without naming us as the actor, so it makes a claim about how somebody else's artifact came to exist`,
        });
      }
    }
  }
  return out;
}

/** Throws rather than returns. Every statement builder calls this on its own output. */
export function assertPermitted(text: string): string {
  const violations = findClaimViolations(text);
  if (violations.length > 0) throw new ForbiddenClaimError(violations);
  return text;
}
