/**
 * The side-by-side figure, and the disclaimer band that has to survive every export.
 *
 * This is the legally load-bearing module in the package. `design/SELF-AUDIT.md` risk 3 states the
 * problem exactly: the artifact that travels is a PNG, produced by a code path (og:image, an
 * export button, somebody's own screenshot key) that is not the code path a legal review reads.
 * Three named failure modes follow from that, and the layout below is built to make each one
 * impossible rather than unlikely:
 *
 *  1. THE BAND DOES NOT FIT, so somebody shrinks it "just for the card". Here the disclaimer,
 *     the panel labels and the panel meta lines all render at ONE integer scale. There is no
 *     independent size to shrink. If the whole composition cannot fit at scale 1, `composeFigure`
 *     THROWS. A thrown export is a bug report; a silently shrunk disclaimer is an exhibit.
 *
 *  2. A CROP SEPARATES THE PANELS FROM THE BAND. The band is inside the same 1px border as both
 *     panels, and the border is the outermost thing in the raster, so the default crop that keeps
 *     the figure keeps the band. `checkDisclaimerProminence` verifies that enclosure from pixels.
 *
 *  3. THE PANELS ARE ASYMMETRIC, so the layout makes an accusation the copy then has to walk back.
 *     Both plates are computed to identical width and height and mirrored about the card centre,
 *     and `checkPanelSymmetry` asserts it. The test goes further and composes the same image into
 *     both panels, then compares the two crops byte for byte.
 *
 * Everything renders into our own `Raster` rather than a browser canvas, because the only test
 * worth having reads the finished pixels back (`ocr.ts`), and a canvas we cannot run headlessly is
 * a canvas whose disclaimer nobody checks.
 */

import { assertPermitted } from "./claims.js";
import { ADVANCE } from "./font.js";
import type { OcrLine } from "./ocr.js";
import { ocrLines } from "./ocr.js";
import type { Box, Raster } from "./raster.js";
import { INK, MUTED, PAPER, blitFit, createRaster, fillRect, getPixel, hairline, luma, strokeRect, vrule } from "./raster.js";
import { drawParagraph, drawText, glyphHeightPx, layoutParagraph, measureText } from "./text-render.js";

/** The left panel's label. A sentinel: the prominence checker looks for it in the pixels. */
export const SUBMITTED_LABEL = "SUBMITTED";
/**
 * The right panel's label.
 *
 * It names us in the label itself, which is what `design/SURFACES.md` A.5 requires and also what
 * lets the phrase past `claims.ts`: "generated by" is forbidden, "generated by us" is the one
 * permitted completion, because it identifies the actor.
 */
export const RECREATION_LABEL = "GENERATED BY US";

export const DISCLAIMER_HEADING = "READ THIS WITH THE IMAGES ABOVE";

/**
 * Fixed copy. Not rewritten for tone, not shortened for a size, not templated per artifact.
 *
 * Four sentences doing four jobs: attribute the right panel to us, deny that it is evidence about
 * the left panel, deny that any person is being described, and state the single fact the figure
 * actually supports.
 */
export const DISCLAIMER_BODY = [
  "The right-hand panel was produced by us, moments ago, from the prompt on this receipt.",
  "It is not evidence about how the left-hand panel came to exist.",
  "We make no claim about any person.",
  "One fact is shown here: an artifact of this kind is cheap for us to remake.",
].join(" ");

export interface ExportSize {
  readonly id: string;
  readonly width: number;
  readonly height: number;
  /** Why this size exists. Every size is a real distribution surface, not a round number. */
  readonly purpose: string;
}

/**
 * Every size this product can emit a figure at.
 *
 * The OCR test iterates this list, so adding a size adds a test case automatically. That is the
 * point of holding them as data: the failure mode being designed against is a new export size
 * added for a campaign, at a shape nobody rendered the disclaimer into.
 */
export const EXPORT_SIZES: readonly ExportSize[] = [
  { id: "og", width: 1200, height: 630, purpose: "og:image and Twitter summary_large_image" },
  { id: "square", width: 1080, height: 1080, purpose: "1:1 social post" },
  { id: "portrait", width: 1080, height: 1350, purpose: "4:5 social post, the tallest common feed crop" },
  { id: "story", width: 1080, height: 1920, purpose: "9:16 story and reel frame" },
  { id: "landscape", width: 1600, height: 900, purpose: "16:9 slide and blog hero" },
  { id: "receipt-inline", width: 1128, height: 520, purpose: "the figure block inside the receipt page" },
  { id: "mobile", width: 390, height: 720, purpose: "the 390px viewport, the hardest layout in the product" },
];

export interface PanelSpec {
  readonly label: string;
  /** One mono line under the plate. Short: it is a caption, not a paragraph. */
  readonly meta: string;
  readonly image: Raster;
}

export interface FigureSpec {
  readonly submitted: PanelSpec;
  readonly recreation: PanelSpec;
}

export interface FigureLayout {
  readonly size: ExportSize;
  /** The single bordered card. Everything below is inside it. */
  readonly card: Box;
  /** One integer scale for every line of type in the figure. See the header note. */
  readonly textScale: number;
  readonly labelHeightPx: number;
  readonly disclaimerHeightPx: number;
  readonly labelBoxes: readonly [Box, Box];
  readonly plates: readonly [Box, Box];
  readonly metaBoxes: readonly [Box, Box];
  /** The vertical rule, drawn only across the plates so it cannot glue two text bands together. */
  readonly divider: Box;
  /** The 1px horizontal rule between the panels and the band, inside the card. */
  readonly bandRule: Box;
  readonly disclaimerBox: Box;
}

export interface ComposedFigure {
  readonly raster: Raster;
  readonly layout: FigureLayout;
}

export class FigureTooSmallError extends Error {
  constructor(size: ExportSize, needed: number, available: number) {
    super(
      `the figure cannot be composed at ${size.width}x${size.height} ("${size.id}"): the disclaimer band and labels need ${needed}px of height at the smallest legible scale and only ${available}px is available. The figure is not emitted at a size where the disclaimer would have to shrink.`,
    );
    this.name = "FigureTooSmallError";
  }
}

/** Smallest plate we will render. Below this the panels are not a comparison any more. */
const MIN_PLATE_PX = 40;
const MAX_TEXT_SCALE = 4;

function marginFor(size: ExportSize): number {
  return Math.max(4, Math.round(Math.min(size.width, size.height) * 0.015));
}

function padFor(size: ExportSize): number {
  return Math.max(6, Math.round(size.width * 0.02));
}

/**
 * Snap an x coordinate onto the figure's glyph grid.
 *
 * Two labels on the same row land in one OCR band, and the decoder walks that band on a fixed
 * 6-cell pitch from the first inked pixel. If the second label does not sit on the same pitch its
 * glyphs are sampled off-centre and decode as noise, and a band that is mostly noise is DISCARDED
 * by the decoder - which would silently remove the panel labels from the measurement the whole
 * legal test depends on. Snapping is what makes the round trip exact.
 */
function snapToGrid(x: number, originX: number, scale: number): number {
  const pitch = ADVANCE * scale;
  return originX + Math.max(0, Math.round((x - originX) / pitch)) * pitch;
}

interface Vertical {
  readonly labelY: number;
  readonly plateY: number;
  readonly plateH: number;
  readonly metaY: number;
  readonly ruleY: number;
  readonly headingY: number;
  readonly bodyY: number;
  readonly bodyHeight: number;
  readonly lines: readonly string[];
  readonly lineHeight: number;
}

function verticalFor(card: Box, pad: number, scale: number): Vertical | null {
  const glyph = glyphHeightPx(scale);
  const innerW = card.w - 2 * pad;
  const paragraph = layoutParagraph(DISCLAIMER_BODY, scale, innerW);
  const headingHeight = paragraph.lineHeight;

  const labelY = card.y + pad;
  const plateY = labelY + glyph + pad;
  // Everything below the plate, measured from the bottom up, so the plate gets what is left and
  // never the other way round. The band's height is an input to the layout, not a remainder.
  const bodyHeight = paragraph.height;
  const bodyY = card.y + card.h - pad - bodyHeight;
  const headingY = bodyY - headingHeight;
  const ruleY = headingY - pad;
  const metaY = ruleY - pad - glyph;
  const plateH = metaY - pad - plateY;
  if (plateH < MIN_PLATE_PX) return null;
  return {
    labelY,
    plateY,
    plateH,
    metaY,
    ruleY,
    headingY,
    bodyY,
    bodyHeight,
    lines: paragraph.lines,
    lineHeight: paragraph.lineHeight,
  };
}

/**
 * Compose the figure.
 *
 * Throws rather than degrading. `FigureTooSmallError` and `ForbiddenClaimError` are both preferable
 * to an emitted PNG, because a PNG is the thing that ends up in somebody else's timeline.
 */
export function composeFigure(spec: FigureSpec, size: ExportSize): ComposedFigure {
  for (const text of [spec.submitted.label, spec.submitted.meta, spec.recreation.label, spec.recreation.meta]) {
    assertPermitted(text);
  }
  assertPermitted(DISCLAIMER_HEADING);
  assertPermitted(DISCLAIMER_BODY);

  const margin = marginFor(size);
  const pad = padFor(size);
  const card: Box = {
    x: margin,
    y: margin,
    w: size.width - 2 * margin,
    h: size.height - 2 * margin,
  };
  if (card.w <= 4 * pad || card.h <= 4 * pad) throw new FigureTooSmallError(size, 4 * pad, Math.min(card.w, card.h));

  let scale = Math.min(MAX_TEXT_SCALE, Math.max(1, Math.round(size.width / 450)));
  let vertical = verticalFor(card, pad, scale);
  while (vertical === null && scale > 1) {
    scale -= 1;
    vertical = verticalFor(card, pad, scale);
  }
  if (vertical === null) {
    const atOne = layoutParagraph(DISCLAIMER_BODY, 1, card.w - 2 * pad);
    throw new FigureTooSmallError(size, atOne.height + 2 * atOne.lineHeight + 4 * pad, card.h);
  }

  const v = vertical;
  const glyph = glyphHeightPx(scale);
  const originX = card.x + pad;
  const innerW = card.w - 2 * pad;

  // Equal panels, mirrored about the card centre. Both widths come from ONE number so an odd card
  // width cannot make one panel a pixel wider than the other.
  const gutter = pad * 2;
  const panelW = Math.floor((innerW - gutter) / 2);
  if (panelW < MIN_PLATE_PX) throw new FigureTooSmallError(size, 2 * MIN_PLATE_PX + gutter, innerW);
  const leftX = originX;
  const rightX = card.x + card.w - pad - panelW;

  const raster = createRaster(size.width, size.height, PAPER);
  fillRect(raster, card, PAPER);
  strokeRect(raster, card, INK);

  const plates: [Box, Box] = [
    { x: leftX, y: v.plateY, w: panelW, h: v.plateH },
    { x: rightX, y: v.plateY, w: panelW, h: v.plateH },
  ];
  blitFit(raster, spec.submitted.image, plates[0]);
  blitFit(raster, spec.recreation.image, plates[1]);

  const rightTextX = snapToGrid(rightX, originX, scale);
  const labelBoxes: [Box, Box] = [
    { x: leftX, y: v.labelY, w: measureText(spec.submitted.label, scale), h: glyph },
    { x: rightTextX, y: v.labelY, w: measureText(spec.recreation.label, scale), h: glyph },
  ];
  drawText(raster, spec.submitted.label, labelBoxes[0].x, v.labelY, scale, INK);
  drawText(raster, spec.recreation.label, labelBoxes[1].x, v.labelY, scale, INK);

  const metaBoxes: [Box, Box] = [
    { x: leftX, y: v.metaY, w: measureText(spec.submitted.meta, scale), h: glyph },
    { x: rightTextX, y: v.metaY, w: measureText(spec.recreation.meta, scale), h: glyph },
  ];
  drawText(raster, spec.submitted.meta, metaBoxes[0].x, v.metaY, scale, MUTED);
  drawText(raster, spec.recreation.meta, metaBoxes[1].x, v.metaY, scale, MUTED);

  // Only across the plates. See `snapToGrid` for why it must not cross a text row.
  const dividerX = leftX + panelW + Math.floor(gutter / 2);
  vrule(raster, dividerX, v.plateY, v.plateH, MUTED);
  const divider: Box = { x: dividerX, y: v.plateY, w: 1, h: v.plateH };

  hairline(raster, card.x, v.ruleY, card.w, INK);
  const bandRule: Box = { x: card.x, y: v.ruleY, w: card.w, h: 1 };

  drawText(raster, DISCLAIMER_HEADING, originX, v.headingY, scale, INK);
  drawParagraph(
    raster,
    { lines: v.lines, lineHeight: v.lineHeight, height: v.bodyHeight },
    originX,
    v.bodyY,
    scale,
    INK,
  );

  const disclaimerBox: Box = {
    x: originX,
    y: v.headingY,
    w: innerW,
    h: v.bodyY + v.bodyHeight - v.headingY,
  };

  return {
    raster,
    layout: {
      size,
      card,
      textScale: scale,
      labelHeightPx: glyph,
      disclaimerHeightPx: glyph,
      labelBoxes,
      plates,
      metaBoxes,
      divider,
      bandRule,
      disclaimerBox,
    },
  };
}

/* -------------------------------------------------------------------------------------------- */
/* The checks. Both read pixels, so both work on a figure this package did not compose.           */
/* -------------------------------------------------------------------------------------------- */

export interface BorderBox extends Box {
  readonly found: boolean;
}

/**
 * Recover the outermost bordered rectangle from the pixels.
 *
 * A column that is ink for most of the image height, and a row that is ink for most of its width,
 * are the card border. Reading it back rather than trusting the layout is what makes "the band is
 * inside the same border as both panels" a statement about the finished image.
 */
export function findEnclosingBorder(r: Raster): BorderBox {
  // Columns first. A border column is ink for nearly the full image height; a dark panel plate is
  // ink for a third of it at most, so nothing in the artwork can be mistaken for the frame.
  const inkyColumns: number[] = [];
  for (let x = 0; x < r.width; x += 1) {
    let n = 0;
    for (let y = 0; y < r.height; y += 1) if (luma(getPixel(r, x, y)) < 128) n += 1;
    if (n >= r.height * 0.8) inkyColumns.push(x);
  }
  if (inkyColumns.length < 2) return { x: 0, y: 0, w: 0, h: 0, found: false };
  const x0 = inkyColumns[0] as number;
  const x1 = inkyColumns[inkyColumns.length - 1] as number;

  // Rows are then measured only ACROSS the frame, and have to be all but solid. Two very dark
  // plates side by side can cover most of a row; they cannot cover the gutter and both inner pads
  // as well, so they cannot pass at this threshold and drag the top of the frame down over the
  // panel labels - which would turn a correct figure into a false failure.
  const span = x1 - x0 + 1;
  const inkyRows: number[] = [];
  for (let y = 0; y < r.height; y += 1) {
    let n = 0;
    for (let x = x0; x <= x1; x += 1) if (luma(getPixel(r, x, y)) < 128) n += 1;
    if (n >= span * 0.98) inkyRows.push(y);
  }
  if (inkyRows.length < 2) return { x: 0, y: 0, w: 0, h: 0, found: false };
  const y0 = inkyRows[0] as number;
  const y1 = inkyRows[inkyRows.length - 1] as number;
  return { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1, found: true };
}

export interface ProminenceReport {
  readonly ok: boolean;
  readonly problems: readonly string[];
  /** Measured from the pixels. Null when the label line could not be read back at all. */
  readonly labelHeightPx: number | null;
  readonly disclaimerHeightPx: number | null;
  readonly recoveredDisclaimer: string;
  readonly lines: readonly OcrLine[];
}

const norm = (s: string): string => s.toUpperCase().replace(/\s+/g, " ").trim();

/**
 * THE SHIP-BLOCKING CHECK.
 *
 * `design/SELF-AUDIT.md` risk 3 asks for exactly this and calls it the only test in the repository
 * whose failure is a legal exposure rather than a bug: render, OCR, assert the disclaimer is
 * present at >= the panel-label pixel height. Four things are asserted, and each one corresponds to
 * a real way a share card loses its disclaimer:
 *
 *   - the panel labels are readable at all (otherwise the comparison has no denominator);
 *   - the ENTIRE disclaimer body is recoverable, not merely its first line (catches clipping);
 *   - every disclaimer line's measured glyph height is >= the label's (catches shrinking);
 *   - the disclaimer sits inside the same border as both panel labels (catches a band moved
 *     outside the card, and catches a crop that removed it).
 */
export function checkDisclaimerProminence(r: Raster): ProminenceReport {
  const lines = ocrLines(r);
  const problems: string[] = [];

  const labelLine = lines.find((l) => l.text.includes(SUBMITTED_LABEL) && l.text.includes(RECREATION_LABEL));
  if (labelLine === undefined) {
    problems.push(
      `neither panel label was readable in the finished pixels (looked for ${JSON.stringify(SUBMITTED_LABEL)} and ${JSON.stringify(RECREATION_LABEL)} on one line)`,
    );
  }

  const headingLine = lines.find((l) => norm(l.text) === norm(DISCLAIMER_HEADING));
  if (headingLine === undefined) problems.push(`the disclaimer heading ${JSON.stringify(DISCLAIMER_HEADING)} is not in the pixels`);

  const bodyLines = headingLine === undefined ? [] : lines.filter((l) => l.top > headingLine.top);
  const recovered = norm(bodyLines.map((l) => l.text).join(" "));
  const wanted = norm(DISCLAIMER_BODY.replace(/[^A-Za-z0-9 .,:\-/()$?!'%+=*]/g, "?"));
  if (!recovered.includes(wanted)) {
    problems.push(
      `the disclaimer body was not recovered in full from the pixels. wanted: ${JSON.stringify(wanted)} / read: ${JSON.stringify(recovered)}`,
    );
  }

  const band = headingLine === undefined ? [] : [headingLine, ...bodyLines];
  const disclaimerHeightPx = band.length === 0 ? null : Math.min(...band.map((l) => l.glyphHeightPx));
  const labelHeightPx = labelLine?.glyphHeightPx ?? null;

  if (labelHeightPx !== null && disclaimerHeightPx !== null && disclaimerHeightPx < labelHeightPx) {
    problems.push(
      `the disclaimer renders at ${disclaimerHeightPx}px where the panel labels render at ${labelHeightPx}px. The band must never be smaller than the labels it qualifies.`,
    );
  }

  const border = findEnclosingBorder(r);
  if (!border.found) {
    problems.push("no enclosing border was found, so the disclaimer cannot be shown to share a frame with the panels");
  } else {
    const inside = (l: OcrLine): boolean =>
      l.top >= border.y && l.top + l.glyphHeightPx <= border.y + border.h && l.left >= border.x;
    if (labelLine !== undefined && !inside(labelLine)) problems.push("the panel labels fall outside the enclosing border");
    for (const l of band) {
      if (!inside(l)) {
        problems.push(`a disclaimer line falls outside the enclosing border: ${JSON.stringify(l.text)}`);
        break;
      }
    }
  }

  return {
    ok: problems.length === 0,
    problems,
    labelHeightPx,
    disclaimerHeightPx,
    recoveredDisclaimer: recovered,
    lines,
  };
}

export interface SymmetryReport {
  readonly ok: boolean;
  readonly problems: readonly string[];
}

/**
 * The panels must be interchangeable as objects.
 *
 * `design/SURFACES.md` A.5: "If the recreation is styled as the answer and the original as the
 * evidence, the layout has made an accusation the copy then has to walk back." Equal plate size,
 * equal label row, and equal distance from each outer edge.
 */
export function checkPanelSymmetry(layout: FigureLayout): SymmetryReport {
  const problems: string[] = [];
  const [a, b] = layout.plates;
  if (a.w !== b.w || a.h !== b.h) problems.push(`plates differ in size: ${a.w}x${a.h} vs ${b.w}x${b.h}`);
  if (a.y !== b.y) problems.push(`plates differ in vertical position: ${a.y} vs ${b.y}`);
  const leftInset = a.x - layout.card.x;
  const rightInset = layout.card.x + layout.card.w - (b.x + b.w);
  if (leftInset !== rightInset) problems.push(`plates are not mirrored: ${leftInset}px from the left edge, ${rightInset}px from the right`);
  const [la, lb] = layout.labelBoxes;
  if (la.y !== lb.y || la.h !== lb.h) problems.push("the two panel labels are not on the same row at the same size");
  const [ma, mb] = layout.metaBoxes;
  if (ma.y !== mb.y || ma.h !== mb.h) problems.push("the two panel meta lines are not on the same row at the same size");
  if (layout.disclaimerHeightPx < layout.labelHeightPx) {
    problems.push(`the layout allocates ${layout.disclaimerHeightPx}px to the disclaimer and ${layout.labelHeightPx}px to the labels`);
  }
  return { ok: problems.length === 0, problems };
}
