import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it } from "vitest";

import ReceiptPage, { generateStaticParams } from "@/app/receipt/[id]/page";
import {
  DISCLAIMER_BODY,
  DISCLAIMER_HEADING,
  RECREATION_ALT_PREFIX,
  reproductionFor,
} from "@/lib/reproduction";
import { SAMPLE_IDS } from "@/lib/sample-ids";

/**
 * THE PAGE, RENDERED. The hole this file closes.
 *
 * The export route and the compositor were both tested end to end, and the receipt PAGE was
 * not tested at all. So a page that answered 500 in a browser left the whole suite green:
 * the only way to find out was to open it, and the only error Next surfaced for it was
 * "Jest worker encountered 2 child process exceptions, exceeding retry limit", which names
 * neither the module nor the line.
 *
 * These tests render the shipped route module - the default export, plus
 * `generateStaticParams`, which is a SEPARATE entry point that Next evaluates in its own
 * worker and which therefore fails on its own. Anything that throws while the page's module
 * graph loads, or while the tree renders, is a red test here instead of a 500 there.
 *
 * All four reproduction states are covered because they are four different subtrees of
 * `ReproductionFigure`, and only one of them (`succeeded`) renders plates at all.
 */

const render = async (id: string): Promise<string> =>
  renderToStaticMarkup(
    await ReceiptPage({ params: Promise.resolve({ id }), searchParams: Promise.resolve({}) }),
  );

describe("the receipt page renders", () => {
  it("evaluates generateStaticParams without loading the scoring corpus", () => {
    // Next runs this in its own process. It must not need `server-only`, the corpus, or any
    // of the report machinery: it is a list of four strings.
    expect(generateStaticParams()).toEqual(SAMPLE_IDS.map((id) => ({ id })));
    expect(SAMPLE_IDS.length).toBe(4);
  });

  it.each(SAMPLE_IDS)("%s answers HTML rather than throwing", async (id) => {
    const html = await render(id);
    expect(html).toContain("Slop Scorer / Receipt");
    expect(html).toContain(id);
    // The figure is on every receipt, in every state. There is no state that omits it.
    expect(html).toContain("<figure");
  });

  it("succeeded: both panels, and the disclaimer inside the same frame", async () => {
    const id = "4F2A-9C";
    expect(reproductionFor(id).state).toBe("succeeded");
    const html = await render(id);

    expect(html).toContain("SUBMITTED");
    expect(html).toContain("GENERATED BY US");
    expect(html).toContain(DISCLAIMER_HEADING);
    expect(html).toContain(DISCLAIMER_BODY);
    expect(html).toContain(RECREATION_ALT_PREFIX);

    // Same frame, literally: the band is inside the <figure>, not after it. Taking the
    // substring from <figure to </figure> and finding the disclaimer in it is the check.
    const figure = html.slice(html.indexOf("<figure"), html.indexOf("</figure>"));
    expect(figure).toContain("SUBMITTED");
    expect(figure).toContain("GENERATED BY US");
    expect(figure).toContain(DISCLAIMER_HEADING);
    expect(figure).toContain(DISCLAIMER_BODY);

    // Symmetric panels: one component renders both, so both carry the same class list.
    const panels = figure.match(/class="flex min-w-0 flex-1 basis-0 flex-col gap-3 p-5"/g);
    expect(panels).toHaveLength(2);

    // The export button only exists where there is a figure to export.
    expect(html).toContain("Export this figure as a PNG");
  });

  it("could_not_reproduce: says so, and offers no export", async () => {
    const id = "8B10-2D";
    expect(reproductionFor(id).state).toBe("could_not_reproduce");
    const html = await render(id);

    expect(html).toContain("WE TRIED AND FAILED. THAT IS A FACT ABOUT OUR PIPELINE.");
    expect(html).toContain("Could not reproduce");
    expect(html).toContain("Time spent before we stopped: 21.3 s");
    expect(html).not.toContain("GENERATED BY US");
    expect(html).not.toContain("Export this figure as a PNG");
  });

  it("refused: prints the refusal code and offers no export", async () => {
    const id = "C7E3-51";
    expect(reproductionFor(id).state).toBe("refused");
    const html = await render(id);

    expect(html).toContain("WE DECLINED TO RUN THIS ONE.");
    expect(html).toContain("Refusal code: identifiable_person");
    expect(html).not.toContain("GENERATED BY US");
    expect(html).not.toContain("Export this figure as a PNG");
  });

  it("not_configured: nothing ran, and absence is not a finding", async () => {
    const id = "A05E-13";
    expect(reproductionFor(id).state).toBe("not_configured");
    const html = await render(id);

    expect(html).toContain("NO REPRODUCTION WAS ATTEMPTED.");
    expect(html).toContain("Absence of a reproduction here is not a finding.");
    expect(html).not.toContain("GENERATED BY US");
    expect(html).not.toContain("Export this figure as a PNG");
  });

  it("an unknown receipt id calls notFound() rather than rendering an empty receipt", async () => {
    await expect(render("ZZZZ-99")).rejects.toThrow();
  });
});
