/**
 * "This is AI" must be unspeakable.
 *
 * `market-check-reproduction.md` (e) names inverse harassment as the single biggest risk in this
 * product: a convincing side-by-side is read as proof, travels further than a percentage, and every
 * documented harm in `image-detection-reality.md` is a tool's output being wielded by someone who
 * did not read the caveat. The control is that the package cannot form the sentence.
 *
 * Three layers, all here:
 *
 *  1. THE GUARD ITSELF, mutation-tested. Known-bad sentences must be rejected, known-good ones
 *     accepted. A phrase list that no longer matches anything is decoration.
 *  2. EVERY SENTENCE THE PACKAGE CAN EMIT AT RUNTIME - every statement, caveat, detail and
 *     confounder line off every arm of the result union, driven through the real pipeline.
 *  3. EVERY STRING LITERAL IN THE SOURCE. Layer 2 only covers copy somebody remembered to reach.
 *     This one walks the source with a tokenizer, so a sentence added tomorrow is covered whether
 *     or not a test reaches it.
 */

import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  CONFOUNDER_TEXT,
  CONSENT_STATEMENT_TEXT,
  COULD_NOT_REPRODUCE_CAVEAT,
  DEFERRED_MODALITIES,
  DISCLAIMER_BODY,
  DISCLAIMER_HEADING,
  FORBIDDEN_CLAIM_PHRASES,
  FORBIDDEN_PROVIDERS,
  ForbiddenClaimError,
  MockProvider,
  OUT_OF_SCOPE_DETAIL,
  PERMITTED_VERBATIM_QUOTATIONS,
  ProviderRegistry,
  RECREATION_LABEL,
  REAL_PROVIDER_SPECS,
  REFUSAL_TEXT,
  ReproductionPipeline,
  SUBMITTED_LABEL,
  SUCCESS_CAVEAT,
  assertPermitted,
  deterministicRuntime,
  findClaimViolations,
  formatAggregate,
  neutralizeSelfAttribution,
  realProviders,
} from "@slop/reproduce";
import { FORBIDDEN_VERDICT_PHRASES } from "@slop/core";
import { HeuristicFaceDetector } from "@slop/reproduce";
import { consentFor, faceLikeRaster, imageInput, siteInput, textInput } from "./fixtures.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.resolve(here, "../src");

describe("the guard is a real guard", () => {
  it("inherits core's list wholesale rather than restating it", () => {
    for (const phrase of FORBIDDEN_VERDICT_PHRASES) {
      expect(FORBIDDEN_CLAIM_PHRASES, `core banned ${JSON.stringify(phrase)} and this package did not`).toContain(
        phrase,
      );
    }
    expect(FORBIDDEN_CLAIM_PHRASES.length).toBeGreaterThan(FORBIDDEN_VERDICT_PHRASES.length);
  });

  const knownBad: readonly string[] = [
    "This is AI.",
    "This image is AI-generated.",
    "The creator used a model.",
    "It was generated by a diffusion model.",
    "This is human.",
    "This is human-made, so no finding.",
    "Verified human.",
    "We detected undisclosed AI in this artifact.",
    "Our confidence that this is machine output is high.",
    "This proves the artifact was faked.",
    "The author wrote this by hand.",
    "The image was rendered by a model.",
    "Someone made this with a generator.",
  ];

  for (const sentence of knownBad) {
    it(`refuses to emit: ${JSON.stringify(sentence)}`, () => {
      expect(findClaimViolations(sentence).length, sentence).toBeGreaterThan(0);
      expect(() => assertPermitted(sentence)).toThrow(ForbiddenClaimError);
    });
  }

  const knownGood: readonly string[] = [
    "We remade this in 8.4 s, for $0.0039, using the model and the prompt printed on this receipt.",
    "The right-hand panel was produced by us, moments ago.",
    "We could not remake this.",
    "This artifact is cheap for us to remake.",
    "We make no claim about any person.",
    "GENERATED BY US",
  ];

  for (const sentence of knownGood) {
    it(`allows: ${JSON.stringify(sentence)}`, () => {
      expect(findClaimViolations(sentence), sentence).toEqual([]);
    });
  }

  it("the self-attribution carve-out is exactly as narrow as it looks", () => {
    // Permitted, because it names the actor.
    expect(neutralizeSelfAttribution("generated by us")).toBe("generated");
    expect(neutralizeSelfAttribution("made by slop scorer")).toBe("made");
    // Not permitted: any other completion of the same verb.
    expect(neutralizeSelfAttribution("generated by a model")).toBe("generated by a model");
    expect(findClaimViolations("Generated by a model.").length).toBeGreaterThan(0);
    // And the actor test is word-bounded, so "focus" does not read as "us".
    expect(findClaimViolations("The focus was generated overnight.").length).toBeGreaterThan(0);
  });

  it("the verbatim-quotation allowlist has exactly one entry", () => {
    // The only place in the package where the guard can be told to look away. An allowlist that can
    // grow quietly is a hole, so its size is pinned rather than described.
    expect(PERMITTED_VERBATIM_QUOTATIONS.length).toBe(1);
    expect(PERMITTED_VERBATIM_QUOTATIONS[0]).toContain("affirmative, conscious, and voluntary");
  });

  it("a sentence is still checked when it is a bare label or a list item", () => {
    expect(findClaimViolations("SUBMITTED\nAI-GENERATED\nEXPORT").length).toBeGreaterThan(0);
  });
});

describe("every sentence the pipeline can emit at runtime", () => {
  const collected: string[] = [];

  it("drives every arm of the result union and every fixed copy constant", async () => {
    const runtime = deterministicRuntime();
    const nowMs = runtime.clock.now();

    const withProvider = (behaviour: "produce" | "safety_refusal" | "capability_gap") =>
      new ReproductionPipeline({
        registry: new ProviderRegistry()
          .register(new MockProvider({ modality: "text", behaviour }))
          .register(new MockProvider({ modality: "image", behaviour }))
          .register(new MockProvider({ modality: "website-from-screenshot", behaviour })),
        faceDetector: new HeuristicFaceDetector(),
        runtime,
      });

    const inputs = [textInput(), imageInput(), siteInput()];
    for (const input of inputs) {
      for (const behaviour of ["produce", "safety_refusal", "capability_gap"] as const) {
        const result = await withProvider(behaviour).run({
          input,
          consent: consentFor(input.artifact.artifactId, nowMs),
        });
        collected.push(result.statement);
        if ("caveat" in result) collected.push(result.caveat);
        if ("detail" in result) collected.push(result.detail);
      }
    }

    // The refused arm, for real, through the face gate.
    const facePipeline = new ReproductionPipeline({
      registry: new ProviderRegistry().register(new MockProvider({ modality: "image" })),
      faceDetector: new HeuristicFaceDetector(),
      runtime,
    });
    const faceInput = imageInput(faceLikeRaster(), "art_face");
    const refused = await facePipeline.run({
      input: faceInput,
      consent: consentFor(faceInput.artifact.artifactId, nowMs),
    });
    collected.push(refused.statement);
    if ("detail" in refused) collected.push(refused.detail);

    // The not_configured arm, for real, through the real-provider catalogue with no transport.
    const bare = new ReproductionPipeline({
      registry: new ProviderRegistry(),
      runtime,
    });
    for (const provider of realProviders()) void provider;
    const unconfigured = await bare.run({
      input: textInput(),
      consent: consentFor("art_text", nowMs),
    });
    collected.push(unconfigured.statement);
    if ("detail" in unconfigured) collected.push(unconfigured.detail);

    // Fixed copy that a renderer reaches directly.
    collected.push(
      SUCCESS_CAVEAT,
      COULD_NOT_REPRODUCE_CAVEAT,
      OUT_OF_SCOPE_DETAIL,
      DISCLAIMER_HEADING,
      DISCLAIMER_BODY,
      SUBMITTED_LABEL,
      RECREATION_LABEL,
      CONSENT_STATEMENT_TEXT,
      ...Object.values(CONFOUNDER_TEXT),
      ...Object.values(REFUSAL_TEXT),
      ...FORBIDDEN_PROVIDERS.map((f) => f.reason),
      ...DEFERRED_MODALITIES.map((d) => d.reason),
      ...REAL_PROVIDER_SPECS.map((s) => s.note),
      formatAggregate(facePipeline.log.aggregate()),
    );

    // Denominator. Without it the assertion below would pass over an empty list.
    expect(collected.length).toBeGreaterThan(40);
    expect(collected.some((s) => s.includes("could not remake"))).toBe(true);
    expect(collected.some((s) => s.includes("did not run this"))).toBe(true);
    expect(collected.some((s) => s.includes("did not attempt this"))).toBe(true);
    expect(collected.some((s) => s.includes("remade this in"))).toBe(true);
  });

  it("finds no forbidden claim in any of them", () => {
    const violations = collected.flatMap((text) =>
      findClaimViolations(text).map((v) => `${v.kind}: ${v.detail}\n  in: ${v.sentence}`),
    );
    expect(violations, violations.join("\n")).toEqual([]);
  });
});

/* ---------------------------------------------------------------------------------------------- */

/**
 * Pull every string literal out of TypeScript source, ignoring comments AND regular expressions.
 *
 * The regex handling is not fussiness. The first draft of this scanner did not have it, and an
 * apostrophe inside a character class in `compose.ts` opened a phantom string that swallowed several
 * hundred characters of comment prose - which then reported a violation that did not exist, in text
 * that is not copy. A scanner that misreads its input is the same class of bug this repository
 * exists to catch, pointed the other way.
 */
function stringLiterals(source: string): string[] {
  const out: string[] = [];
  /** After one of these, a `/` opens a regular expression rather than dividing. */
  const REGEX_PRECEDERS = new Set(["(", ",", "=", ":", "[", "!", "&", "|", "?", "{", "}", ";", "+", "*", "\n", ""]);
  let lastSignificant = "";
  let i = 0;
  while (i < source.length) {
    const ch = source[i] as string;
    const next = source[i + 1];
    if (ch === "/" && next === "/") {
      while (i < source.length && source[i] !== "\n") i += 1;
      continue;
    }
    if (ch === "/" && next === "*") {
      i += 2;
      while (i < source.length && !(source[i] === "*" && source[i + 1] === "/")) i += 1;
      i += 2;
      continue;
    }
    if (ch === "/" && REGEX_PRECEDERS.has(lastSignificant)) {
      i += 1;
      let inClass = false;
      while (i < source.length) {
        const c = source[i];
        if (c === "\\") {
          i += 2;
          continue;
        }
        if (c === "[") inClass = true;
        else if (c === "]") inClass = false;
        else if (c === "\n") break;
        else if (c === "/" && !inClass) break;
        i += 1;
      }
      i += 1;
      lastSignificant = "/";
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      const quote = ch;
      i += 1;
      let buf = "";
      while (i < source.length && source[i] !== quote) {
        if (source[i] === "\\") {
          i += 2;
          buf += " ";
          continue;
        }
        // Template holes are not copy. Replace with a space so the words either side do not fuse.
        if (quote === "`" && source[i] === "$" && source[i + 1] === "{") {
          let depth = 1;
          i += 2;
          while (i < source.length && depth > 0) {
            if (source[i] === "{") depth += 1;
            if (source[i] === "}") depth -= 1;
            i += 1;
          }
          buf += " ";
          continue;
        }
        buf += source[i];
        i += 1;
      }
      i += 1;
      out.push(buf);
      lastSignificant = '"';
      continue;
    }
    if (!/\s/.test(ch)) lastSignificant = ch;
    else if (ch === "\n") lastSignificant = "\n";
    i += 1;
  }
  return out;
}

/**
 * A lowercase identifier-shaped literal is a code, not copy: `"produced"`, `"safety_refusal"`,
 * `"image/png"`. Every reader-facing string in this package is sentence-cased or upper-cased, so
 * this filter cannot hide one - and it is narrow enough that `"ai-generated"` in a sentence, or
 * `"AI-generated"` alone, still goes through the guard.
 */
const isCode = (literal: string): boolean => /^[a-z0-9_./:-]*$/.test(literal);

async function sourceFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await sourceFiles(full)));
    else if (entry.name.endsWith(".ts")) out.push(full);
  }
  return out;
}

/**
 * `claims.ts` is the one exclusion, and it is unavoidable: it has to WRITE every phrase it bans, so
 * scanning it would make this test permanently red. Pinning the exclusion list at length one is what
 * stops it from quietly becoming the place inconvenient copy goes to live.
 */
const EXCLUDED = ["claims.ts"];

describe("every string literal in the source", () => {
  it("scans a non-empty set of files and literals, and sees the copy it is supposed to see", async () => {
    const files = await sourceFiles(srcDir);
    expect(files.length).toBeGreaterThan(12);
    const literals = (await Promise.all(files.map((f) => readFile(f, "utf8")))).flatMap(stringLiterals);
    expect(literals.length).toBeGreaterThan(200);
    // Sentinels: if the tokenizer breaks, these disappear and everything below goes vacuously green.
    expect(literals).toContain(DISCLAIMER_HEADING);
    expect(literals.some((l) => l.includes("cheap for us to remake"))).toBe(true);
    expect(literals.some((l) => l.includes("affirmative, conscious"))).toBe(true);
  });

  it("keeps the exclusion list at exactly one file", () => {
    expect(EXCLUDED).toEqual(["claims.ts"]);
  });

  it("contains no forbidden claim", async () => {
    const files = (await sourceFiles(srcDir)).filter((f) => !EXCLUDED.includes(path.basename(f)));
    const violations: string[] = [];
    for (const file of files) {
      for (const literal of stringLiterals(await readFile(file, "utf8"))) {
        if (isCode(literal)) continue;
        for (const v of findClaimViolations(literal)) {
          violations.push(`${path.relative(srcDir, file)}: [${v.kind}] ${v.detail}\n    in: ${v.sentence}`);
        }
      }
    }
    expect(violations, violations.join("\n")).toEqual([]);
  });
});
