/**
 * The credential. Every word of it is a liability boundary.
 *
 * `human-verification-licensing.md` lists "the exact wording of the badge and its public definition
 * page" as item 3 on the things that need an attorney before shipping, and section 7 says plainly:
 * do not ship the words "Verified Human". So the wording here is assembled from FACTS AND COUNTS
 * by a builder, run through `assertAttestable`, and stored verbatim on the row - because a
 * credential whose text is regenerated by later code is a credential nobody can be held to.
 *
 * THE SHAPE OF THE CLAIM, and why each clause is the weakest true version of itself:
 *
 *   "We recorded N steps of this file's history, the first at T."
 *      Ours, observed, countable. Not "the complete history": we saw what was sent.
 *   "The chain root was timestamped by K independent authorities in J jurisdictions."
 *      A count of tokens we hold, each independently checkable by the reader.
 *   "The earliest of those timestamps is G."
 *      Proof of existence before an instant. Exactly what RFC 3161 attests and no more.
 *   "A recorded process shows a tool was operated. It does not show who operated it."
 *      Mandatory. Present on every credential, not just the weak ones.
 *
 * What is deliberately absent: any adjective describing the maker, any score, any pass or fail, and
 * any sentence a platform could quote as a boolean.
 */

import type { NotaryCredentialRow, NotaryTimestampRow } from "@slop/db";
import { assertAttestable } from "./claims.js";
import { TOKEN_VERIFICATION_SCOPE } from "./tsa.js";

/** Bumped when the wording changes. A stored credential records which version it speaks. */
export const STATEMENT_VERSION = 1 as const;

/**
 * The limitation, on every credential, in full.
 *
 * Not a footnote and not conditional on the evidence being weak. The evasion result behind it is
 * general: a person transcribing model output produces a near-genuine process trace, so no amount
 * of recorded process moves the claim from "a tool was operated" to anything about a person.
 */
export const LIMITATION =
  "A recorded process shows that a tool was operated over time. It does not show who operated it, " +
  "and it does not show where the content came from. We make no claim about any person.";

/** The second mandatory line: what we did not check about the tokens. */
export const VERIFICATION_CAVEAT =
  `We checked that each authority returned a granted status over the exact root we submitted. ` +
  `We did not check the signature on any token against its authority's certificate chain. ` +
  `Each token is stored in full so it can be checked independently: ${TOKEN_VERIFICATION_SCOPE.independentCheck}.`;

export interface CredentialFacts {
  readonly eventCount: number;
  readonly firstDeclaredAt: string | null;
  readonly lastDeclaredAt: string | null;
  readonly rootSha256: string;
  readonly grantedTimestamps: readonly NotaryTimestampRow[];
  /** Authorities that answered with a refusal or did not answer. Counted, never hidden. */
  readonly failedAuthorities: number;
  /** Defects the chain check found. A credential over a broken chain must say so. */
  readonly chainDefects: readonly string[];
  readonly recordingSummary: string | null;
}

const plural = (n: number, one: string, many: string): string => `${n} ${n === 1 ? one : many}`;

/**
 * Build the statement.
 *
 * Reads like prose, is assembled like a table. Every number in it comes from `facts`, which is why
 * there is no path that produces a stronger sentence than the evidence: a chain with two events and
 * one timestamp says two and one.
 */
export function buildStatement(facts: CredentialFacts): string {
  const jurisdictions = new Set(facts.grantedTimestamps.map((t) => t.jurisdiction));
  const genTimes = facts.grantedTimestamps
    .map((t) => t.genTime)
    .filter((g): g is string => g !== null)
    .sort();

  const lines: string[] = [];

  lines.push(
    `We recorded ${plural(facts.eventCount, "step", "steps")} of this file's history` +
      (facts.firstDeclaredAt === null ? "." : `, the first of them dated ${facts.firstDeclaredAt}.`),
  );

  if (facts.grantedTimestamps.length === 0) {
    // The honest empty case. A chain with no timestamp is a chain we could have written yesterday,
    // and the credential says exactly that rather than leaning on the hash.
    lines.push(
      `No timestamp authority has stamped this chain, so nothing here establishes that the record ` +
        `existed before now.`,
    );
  } else {
    lines.push(
      `The root of that record, ${facts.rootSha256}, was timestamped by ` +
        `${plural(facts.grantedTimestamps.length, "independent authority", "independent authorities")} ` +
        `in ${plural(jurisdictions.size, "jurisdiction", "jurisdictions")}.`,
    );
    if (genTimes[0] !== undefined) {
      lines.push(`The earliest of those timestamps is ${genTimes[0]}, so the record existed by then.`);
    }
  }

  if (facts.failedAuthorities > 0) {
    lines.push(
      `${plural(facts.failedAuthorities, "authority", "authorities")} we asked did not return a usable token.`,
    );
  }

  if (facts.recordingSummary !== null) lines.push(facts.recordingSummary);

  if (facts.chainDefects.length > 0) {
    lines.push(
      `The recorded chain did not re-verify cleanly: ${facts.chainDefects.join("; ")}. ` +
        `Read this credential as a description of what was recorded, not as an intact record.`,
    );
  }

  lines.push(VERIFICATION_CAVEAT);
  lines.push(LIMITATION);

  return assertAttestable(lines.join(" "));
}

export interface IssueInput extends CredentialFacts {
  readonly credentialId: string;
  readonly chainId: string;
  readonly issuedAt: string;
}

export function issueCredentialRow(input: IssueInput): NotaryCredentialRow {
  const jurisdictions = new Set(input.grantedTimestamps.map((t) => t.jurisdiction));
  const genTimes = input.grantedTimestamps
    .map((t) => t.genTime)
    .filter((g): g is string => g !== null)
    .sort();
  return {
    credentialId: input.credentialId,
    chainId: input.chainId,
    rootSha256: input.rootSha256,
    statement: buildStatement(input),
    statementVersion: STATEMENT_VERSION,
    eventCount: input.eventCount,
    authorityCount: input.grantedTimestamps.length,
    jurisdictionCount: jurisdictions.size,
    earliestGenTime: genTimes[0] ?? null,
    issuedAt: input.issuedAt,
    revokedAt: null,
    revocationReason: null,
  };
}
