import { Badge } from "@/components/ui/badge";
import {
  DISCLAIMER_BODY,
  DISCLAIMER_HEADING,
  recreationAlt,
  type Plate,
  type Reproduction,
} from "@/lib/reproduction";
import { PANEL_ATTR } from "./reveal";

/**
 * THE FIGURE. This is the legally load-bearing block on the site and the one component
 * whose layout is a compliance artifact rather than a design choice.
 *
 * The governing authority, in one line: where the expressed facts are literally true, a
 * publisher is still liable if it did "something beyond the mere reporting of true facts" to
 * endorse the inference, and White v. Fraternal Order of Police, 909 F.2d 512 (D.C. Cir.
 * 1990) illustrates that with a case where PUTTING FIGURES SIDE BY SIDE was itself the
 * affirmative evidence that the inference was intended. Our whole product is a side by side.
 * So the correction has to live inside the juxtaposition, not underneath it.
 *
 * What that means concretely, and what a reviewer should check:
 *
 *   SAME FRAME    the disclaimer is a child of the same bordered element as both panels.
 *                 There is no layout, viewport, crop or export in which the panels appear
 *                 without it. That is why the band is inside <figure> and not a sibling.
 *   SAME SIZE     the disclaimer heading and body are text-mono-md, which is the same 14px
 *                 token the panel labels SUBMITTED and GENERATED BY US use. One token, used
 *                 twice, so the two cannot drift apart in a later edit.
 *   SAME COLOUR   both are text-ink (16.6:1). Neither is muted. A 10px grey footnote is the
 *                 precise defect the legal memo names as insufficient.
 *   SYMMETRY      identical widths, identical plate treatment, identical label weight, no
 *                 arrow, no highlight on the recreation. If the recreation is styled as "the
 *                 answer" the layout has made the accusation and the copy cannot retract it.
 *
 * MOBILE, and this is a deviation worth stating: design/SELF-AUDIT.md flagged the 390px
 * layout as unsolved and warned that stacking weakens the "same frame" argument. The panels
 * stack below 768px because 527px each does not fit, but they stay inside the same border
 * and the divider simply rotates from a vertical rule to a horizontal one. The disclaimer
 * band stays the last child of the same frame at the same 14px. The "same frame" property is
 * therefore preserved at every width; only the axis changes.
 */

function PlateFigure({
  plate,
  label,
  alt,
  reveal,
}: {
  readonly plate: Plate;
  readonly label: string;
  readonly alt: string;
  readonly reveal?: boolean;
}) {
  // Symmetry is enforced structurally: both panels render through this one component, so
  // there is no per-panel styling hook to diverge. `reveal` moves opacity and nothing else.
  const attrs = reveal ? { [PANEL_ATTR]: "" } : {};
  return (
    <div {...attrs} className="flex min-w-0 flex-1 basis-0 flex-col gap-3 p-5">
      <p className="font-mono text-mono-md font-medium text-ink">{label}</p>
      <div className="border border-hairline bg-surface">
        {/* A plain <img> rather than next/image: these plates are SVG documents we drew for
            this page, next/image would need dangerouslyAllowSVG to touch them, and turning
            that on to render a decorative-free forensic exhibit is a bad trade. Intrinsic
            width and height are set so the box reserves its space and nothing shifts. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={plate.src}
          alt={alt}
          width={plate.width}
          height={plate.height}
          className="block h-auto w-full"
        />
      </div>
      <p className="font-mono text-mono-sm text-ink-muted">{plate.meta}</p>
    </div>
  );
}

function DisclaimerBand() {
  return (
    <div className="border-t border-border-control p-5">
      <p className="font-mono text-mono-md font-medium text-ink">{DISCLAIMER_HEADING}</p>
      <p className="mt-2 max-w-[76ch] font-mono text-mono-md text-ink">{DISCLAIMER_BODY}</p>
    </div>
  );
}

/** A band in the figure's own frame, used by the three non-succeeded states. */
function StateBand({
  chip,
  heading,
  body,
}: {
  readonly chip: string;
  readonly heading: string;
  readonly body: string;
}) {
  return (
    <div className="flex flex-col gap-3 p-5">
      <div className="flex items-center gap-3">
        <Badge
          variant="outline"
          className="rounded-sm border-border-control font-mono text-mono-xs font-medium tracking-[0.06em] text-ink uppercase"
        >
          {chip}
        </Badge>
        <p className="font-mono text-mono-md font-medium text-ink">{heading}</p>
      </div>
      <p className="max-w-[76ch] font-mono text-mono-md text-ink">{body}</p>
    </div>
  );
}

export function ReproductionFigure({
  reproduction,
  className,
}: {
  readonly reproduction: Reproduction;
  readonly className?: string;
}) {
  const frame = `border border-border-control bg-surface-raised ${className ?? ""}`;

  switch (reproduction.state) {
    case "succeeded":
      return (
        <figure data-doc className={frame}>
          {/* The divider is a border on the second panel rather than a separate element, so
              there is no third child that could ever be reordered between the two panels. */}
          <div className="flex flex-col md:flex-row">
            <PlateFigure
              plate={reproduction.submitted}
              label="SUBMITTED"
              alt={reproduction.submitted.describes}
            />
            <div className="border-t border-border-control md:border-t-0 md:border-l" />
            <PlateFigure
              plate={reproduction.recreation}
              label="GENERATED BY US"
              alt={recreationAlt(reproduction.recreation.describes)}
              reveal
            />
          </div>
          <figcaption>
            <DisclaimerBand />
            <p className="border-t border-hairline px-5 py-3 font-mono text-mono-sm text-ink-muted">
              Pipeline: {reproduction.pipeline}
              {reproduction.promptCitedBy
                ? ` The prompt is carried as evidence on ${reproduction.promptCitedBy} below.`
                : ""}
            </p>
          </figcaption>
        </figure>
      );

    case "could_not_reproduce":
      return (
        <figure data-doc className={frame}>
          {reproduction.submitted ? (
            <div className="flex flex-col md:flex-row">
              <PlateFigure
                plate={reproduction.submitted}
                label="SUBMITTED"
                alt={reproduction.submitted.describes}
              />
              {/* No second panel and no placeholder for one. An empty plate opposite the
                  original would imply we produced something and are withholding it. */}
              <div className="hidden flex-1 basis-0 md:block" />
            </div>
          ) : null}
          <figcaption>
            <StateBand
              chip="Could not reproduce"
              heading="WE TRIED AND FAILED. THAT IS A FACT ABOUT OUR PIPELINE."
              body={reproduction.reason}
            />
            <p className="border-t border-hairline px-5 py-3 font-mono text-mono-sm text-ink-muted">
              Time spent before we stopped: {(reproduction.attemptedMs / 1000).toFixed(1)} s. A
              failure to reproduce is not evidence that the artifact was made by hand, and we
              are not offering it as any.
            </p>
          </figcaption>
        </figure>
      );

    case "refused":
      return (
        <figure data-doc className={frame}>
          <figcaption>
            <StateBand
              chip="Refused"
              heading="WE DECLINED TO RUN THIS ONE."
              body={reproduction.reason}
            />
            <p className="border-t border-hairline px-5 py-3 font-mono text-mono-sm text-ink-muted">
              Refusal code: {reproduction.code}. This is a standing rule in the pipeline, applied
              before anything is generated, and it is printed here rather than hidden because a
              refusal we do not disclose is indistinguishable from a failure we are embarrassed by.
            </p>
          </figcaption>
        </figure>
      );

    case "not_configured":
      return (
        <figure data-doc className={frame}>
          <figcaption>
            <StateBand
              chip="Not configured"
              heading="NO REPRODUCTION WAS ATTEMPTED."
              body={reproduction.reason}
            />
            <p className="border-t border-hairline px-5 py-3 font-mono text-mono-sm text-ink-muted">
              Modality: {reproduction.modality}. Nothing ran, so there is nothing to show.
              Absence of a reproduction here is not a finding.
            </p>
          </figcaption>
        </figure>
      );
  }
}
